spring:
  config:
    activate:
      on-profile: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/9oormCinema
    username: root
    password: 8982
